version: "3"

volumes:
  production_traefik: {}


services:
  web:
    build: .
    env_file:
      - .env
    volumes:
      - ./logs/web:/app/logs
    command: uwsgi --http-socket :8000 --chdir /app --wsgi-file /app/config/wsgi.py --master --processes 1 --threads 2

  celery:
    build: .
    env_file:
      - .env
    command: celery -A config.celery_app beat -l info

  worker:
    build: .
    env_file:
      - .env
    command: celery -A config.celery_app worker -l debug

