# Generated by Django 3.0.9 on 2022-04-09 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_category_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='source',
            options={'permissions': ()},
        ),
        migrations.AddField(
            model_name='category',
            name='create_by',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='創建人'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='是否刪除'),
        ),
        migrations.AddField(
            model_name='category',
            name='update_by',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='修改人'),
        ),
        migrations.AddField(
            model_name='news',
            name='create_by',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='創建人'),
        ),
        migrations.AddField(
            model_name='news',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='是否刪除'),
        ),
        migrations.AddField(
            model_name='news',
            name='update_by',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='修改人'),
        ),
        migrations.AddField(
            model_name='reply',
            name='create_by',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='創建人'),
        ),
        migrations.AddField(
            model_name='reply',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='是否刪除'),
        ),
        migrations.AddField(
            model_name='reply',
            name='update_by',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='修改人'),
        ),
        migrations.AddField(
            model_name='source',
            name='create_by',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='創建人'),
        ),
        migrations.AddField(
            model_name='source',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='是否刪除'),
        ),
        migrations.AddField(
            model_name='source',
            name='update_by',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='修改人'),
        ),
        migrations.AddField(
            model_name='tag',
            name='create_by',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='創建人'),
        ),
        migrations.AddField(
            model_name='tag',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='是否刪除'),
        ),
        migrations.AddField(
            model_name='tag',
            name='update_by',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='修改人'),
        ),
        migrations.AddField(
            model_name='telegram',
            name='create_by',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='創建人'),
        ),
        migrations.AddField(
            model_name='telegram',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='是否刪除'),
        ),
        migrations.AddField(
            model_name='telegram',
            name='update_by',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='修改人'),
        ),
        migrations.AlterField(
            model_name='category',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='修改時間'),
        ),
        migrations.AlterField(
            model_name='category',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='創建時間'),
        ),
        migrations.AlterField(
            model_name='news',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='修改時間'),
        ),
        migrations.AlterField(
            model_name='news',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='創建時間'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='修改時間'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='創建時間'),
        ),
        migrations.AlterField(
            model_name='source',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Category', verbose_name='分類'),
        ),
        migrations.AlterField(
            model_name='source',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='修改時間'),
        ),
        migrations.AlterField(
            model_name='source',
            name='name',
            field=models.CharField(max_length=255, verbose_name='來源名稱'),
        ),
        migrations.AlterField(
            model_name='source',
            name='remarks',
            field=models.CharField(blank=True, max_length=255, verbose_name='備註'),
        ),
        migrations.AlterField(
            model_name='source',
            name='status',
            field=models.BooleanField(choices=[(0, '否'), (1, '是')], default=True, verbose_name='啟用狀態'),
        ),
        migrations.AlterField(
            model_name='source',
            name='thumbnail',
            field=models.URLField(blank=True, default='', verbose_name='縮圖網址'),
        ),
        migrations.AlterField(
            model_name='source',
            name='timezone',
            field=models.IntegerField(default=0, verbose_name='時區差'),
        ),
        migrations.AlterField(
            model_name='source',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='創建時間'),
        ),
        migrations.AlterField(
            model_name='source',
            name='url',
            field=models.URLField(unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='修改時間'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='創建時間'),
        ),
        migrations.AlterField(
            model_name='telegram',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='修改時間'),
        ),
        migrations.AlterField(
            model_name='telegram',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='創建時間'),
        ),
    ]
