# Generated by Django 3.0.9 on 2022-06-26 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20220410_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='thumbnail',
            field=models.URLField(max_length=512, verbose_name='縮圖網址'),
        ),
    ]
