# Generated by Django 3.0.9 on 2023-03-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20220918_0111'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['push_status'], name='app_news_push_st_049fc2_idx'),
        ),
    ]
